// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uicuutjdpeavzooytlmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpY3V1dGpkcGVhdnpvb3l0bG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzE3ODEsImV4cCI6MjA2ODgwNzc4MX0.bPM4N96P2dArjE1YVM7G7mVw43tI3bjW4nL4t_UBo4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});